# Generated by Django 5.0.6 on 2024-06-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=78)),
                ('estudiante', models.CharField(max_length=200)),
                ('tema', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=300)),
            ],
        ),
    ]
