# Generated by Django 5.0.6 on 2024-06-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuariosegmento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('E', 'Estudiante'), ('P', 'Profesor')], default='E', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioSegmento',
        ),
    ]
